In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [3]:
# Store the CSV created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/WeatherPy_challenge.csv")
city_data_df = city_data_df.set_index('City_ID')
city_data_df.head(200)

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
City_ID,,,,,,,,,,,,
0,Haines Junction,CA,2020-05-08 22:20:43,60.75,-137.51,58.51,32,75,5.41,broken clouds,0,0
1,Upington,ZA,2020-05-08 22:22:34,-28.45,21.26,59.00,33,0,3.36,clear sky,0,0
2,Busselton,AU,2020-05-08 22:19:37,-33.65,115.33,43.00,75,0,6.42,clear sky,0,0
3,Jamestown,US,2020-05-08 22:19:30,42.10,-79.24,33.01,79,90,11.41,light snow,0,0
4,Esperance,AU,2020-05-08 22:19:54,-33.87,121.90,48.20,93,40,6.93,scattered clouds,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
195,Mazagao,BR,2020-05-08 22:19:11,-0.12,-51.29,86.00,79,40,5.82,scattered clouds,0,0
196,Le Pradet,FR,2020-05-08 22:23:03,43.11,6.02,62.01,87,31,4.70,scattered clouds,0,0
197,Port Hardy,CA,2020-05-08 22:20:37,50.70,-127.42,66.20,42,20,3.36,few clouds,0,0
198,Kelme,LT,2020-05-08 22:23:03,55.63,22.93,44.60,87,0,8.05,clear sky,0,0
199,Axim,GH,2020-05-08 22:23:03,4.87,-2.24,81.75,85,100,7.23,overcast clouds,0,0

In [4]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [5]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for you trip? "))
rain = str(input("Do you want it to be raining? (yes/no) "))
snow = str(input("Do you want it to be snowing? (yes/no) "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for you trip? 85
Do you want it to be raining? (yes/no) no
Do you want it to be snowing? (yes/no) no

In [6]:
#If statements to filter out cities with rain and snow
if rain == "yes":
    rain_response = city_data_df["Rain inches (last 3 hrs)"] != 0
else:
    rain_response = city_data_df["Rain inches (last 3 hrs)"] == 0
if snow == "yes":
    snow_response = city_data_df["Snow inches (last 3 hrs)"] != 0
else:
    snow_response = city_data_df["Snow inches (last 3 hrs)"] == 0

In [7]:
# Filter the dataset to find the cities that fit the criteria
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                      (city_data_df["Max Temp"] >= min_temp) & \
                                      (rain_response) & (snow_response)]

In [8]:
preferred_cities_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
City_ID,,,,,,,,,,,,
5,Mahebourg,MU,2020-05-08 22:19:42,-20.41,57.70,71.60,94,40,4.70,scattered clouds,0,0
16,Hilo,US,2020-05-08 22:19:39,19.73,-155.09,84.20,54,20,9.17,few clouds,0,0
17,Bathsheba,BB,2020-05-08 22:22:37,13.22,-59.52,82.40,69,40,17.22,scattered clouds,0,0
22,Butaritari,KI,2020-05-08 22:19:36,3.07,172.79,82.69,77,100,6.89,overcast clouds,0,0
24,Avarua,CK,2020-05-08 22:19:38,-21.21,-159.78,82.40,74,34,9.17,scattered clouds,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
524,Basco,PH,2020-05-08 22:23:51,20.45,121.97,81.81,75,12,6.24,few clouds,0,0
525,Huarmey,PE,2020-05-08 22:23:52,-10.07,-78.15,72.81,72,4,10.74,clear sky,0,0
528,Sorong,ID,2020-05-08 22:23:52,-0.88,131.25,79.57,86,0,9.84,clear sky,0,0
531,Nhulunbuy,AU,2020-05-08 22:23:52,-12.23,136.77,77.00,83,40,3.36,scattered clouds,0,0
534,Bati,ET,2020-05-08 22:23:53,11.18,40.02,72.21,59,27,1.50,scattered clouds,0,0

In [9]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp and coordinates
hotel_df = preferred_cities_df[["City", "Country", "Current Description", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Current Description,Max Temp,Lat,Lng,Hotel Name
City_ID,,,,,,,
5,Mahebourg,MU,scattered clouds,71.60,-20.41,57.70,
16,Hilo,US,few clouds,84.20,19.73,-155.09,
17,Bathsheba,BB,scattered clouds,82.40,13.22,-59.52,
22,Butaritari,KI,overcast clouds,82.69,3.07,172.79,
24,Avarua,CK,scattered clouds,82.40,-21.21,-159.78,
28,Rikitea,PF,scattered clouds,75.74,-23.12,-134.97,
30,Aitape,PG,broken clouds,80.65,-3.14,142.35,
31,Simbahan,PH,light rain,84.06,6.30,120.58,
33,Kavieng,PG,clear sky,83.89,-2.57,150.80,
40,Puerto Ayora,EC,few clouds,82.40,-0.74,-90.35,

In [10]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

#Iterate through the DataFrame
for index, row in hotel_df.iterrows():
    
    #Get the latitude and longitude
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Use the search term: "lodging" and our latitude and longitude
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    #Make request and get the JSON data from the search
    hotels = requests.get(base_url, params=params).json()
    
    #Grab the first hotel from the results and store the name
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [11]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} & {Max Temp} Â°F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
#Save DataFrame as a CSV file
output_data_file = "weather_data/WeatherPy_vacation.csv"
#Export the City_Data into a CSV
hotel_df.to_csv(output_data_file, index_label="City_ID")